spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

  sentry:
  dsn: https://aee6becd0678cad57aa9b7af287341a6@o4507351491674112.ingest.de.sentry.io/4507351497375824
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  sentry.traces-sample-rate: 1.0

springdoc:
  swagger-ui:
    path: /swagger.html
